### ISSUE TITLE
Provide alternative artifact with different retention

### ISSUE THREAD

**Issue by stephanenicolas** [javax-inject/javax-inject#31]
Dagger 1, Dagger 2 and toothpick process @Inject related annotations at compile time. Thus they don't need the retention= runtime for those annotations. 

On Android, all classes that have fields / methods with runtime retained annotations will be included in the first dex. Having the jsr 330 annotations with this retention leads to first dex exceeding the limit. 

It would be very nice to have you guys deploying 2 artifacts to central, with a modifier so that DI libs can decide which annotation retention they wanna use.

**Comment by cgruber** [comment]
Two artifacts makes things a little problematic, especially if one uses
tools that cross DI products.

If you're using the daggers or toothpick on Android then you should be
proguarding any annotations you don't need away.

**Comment by stephanenicolas** [comment]
Hi @cgruber , thanks for the answer. Actually, on Android it is quite possible to switch between 2 different jars that would contain the annotations. I did a fast test yesterday and I could simply exclude the dependency on the standard javax.inject package, and supply one of my own with the new retention. So this works pretty well (actually it's even more powerful than that as we were using a shaded inject package). 

So the question is: for toothpick to work well like this and not contribute to inflate the first dex, we will need those annotations. So we can provide an artifact with it... but soon dagger would do the same and we can quickly endup with 3 different jars. That's why I think it would be just better if you could provide it. A simple artifact with a jar modifier would be a charm for this use case.

I think this question is also interesting as this is really the only aspect of the JSR 330 that is all about runtime as opposed to compile time that was achieved with the daggers. If we wanted to do it by the book, we should actually have 2 different artifacts with 2 different retention targets for both compile and runtime DI.

**Comment by cgruber** [comment]
Let me be clearer.  I salvaged the javax-inject project from Googlecode but
it would take the jsr expert group to come to a decision and release a new
version to change the API.

The ease of jar swapping is a build system issue, not an Android or server
issue and exists below the level of this spec.  This spec offers specific
annotations.  Reducing their retention would be a breaking api, and tools
that seek to work with it could not.  This is why dagger uses these and
didn't go down the road you're going down.

You are asking for a breaking change and a secondary jar to satisfy a need
that can easily be satisfied by using the tools commonly used to thin out
jars.  While I'm sympathetic to the need, it seems like a solution in
search of a problem.

**Comment by stephanenicolas** [comment]
Not at all @cgruber , we do actually really face the problem, and not only us. https://code.google.com/p/android/issues/detail?id=209084

On Android there is really a side effect of having the retention to high for annotations. But yes, the build system can actually provide a work around. And it can even be completely seamless for devs to use either jars. If there were 2 inject artifacts, app devs could basically completely be free to choose which version to use, without paying respect to the original choice of the libs they use. Which is ideal.

The only question is where the jar comes from. I fully understand that there is a need to get the JSR committee meet about this and I highly doubt it's possible as well ;). So, we are going to provide an optional jar in toothpick. Unfortunately, other compile time DI libs might be doing the same at some point to accommodate this issue of dex limit. 

I am glad we could talk about the issue. Though, I close it as it looks like it cannot be solved at the original javax.inject repo level.
